cw_db/Models/Supplier.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace cw_db.Models
{
    public class Supplier
    {
        public Supplier()
        {
            Orders = new List<Order>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [StringLength(255)]
        public string Category { get; set; } = string.Empty;

        [Required]
        [StringLength(100)]
        public string Address { get; set; } = string.Empty;

        public List<Order>? Orders { get; set; }
    }
}

cw_db/Controllers/SuppliersController.cs
using cw_db.Interfaces;
using cw_db.Models;
using Microsoft.AspNetCore.Mvc;

namespace cw_db.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ISupplierService supplierService;

        public SuppliersController(ISupplierService supplierService)
        {
            this.supplierService = supplierService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await supplierService.GetAll();

            return View(model);
        }

        [Obsolete]
        public IActionResult Create() => View();

        
        [HttpPost]
        public async Task<IActionResult> Create(Supplier supplier)
        {

            await supplierService.Add(supplier);
            return RedirectToAction("Index");
        }


    }
}

cw_db/Views/Suppliers/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<Supplier>

<div class="text-center">
    <table class="table">
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
                <td>@product.Address</td>
                <td>
                    @*<a asp-action="Edit" asp-route-Id="@product.Id">Edit</a>*@
                    <a asp-action="Delete" asp-route-Id="@product.Id">Delete</a>
                </td>
            </tr>
        }
    </table>
    <div>
        @if (ViewContext.HttpContext.User.IsInRole("manager") || ViewContext.HttpContext.User.IsInRole("admin"))
        {

                <form asp-controller="Suppliers" asp-action="Create" method="post">
                <input type="text" class="form-control" placeholder="Name" name="Name" />
                <input type="text" class="form-control" placeholder="Category" name="Category" />
                <input type="text" class="form-control" placeholder="Address" name="Address" />
                <button class="btn btn-dark" type="submit">Create</button>
            </form>
        }
    </div>
    @*<h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>