cw_db/Models/Feedback.cs
using System.ComponentModel.DataAnnotations;

namespace cw_db.Models
{
    public class Feedback
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; } = string.Empty;

        [Required]
        [StringLength(255)]
        public string Content { get; set; } = string.Empty;

        [Range(0, 5, ErrorMessage = "Please enter correct value")]
        public int Rating { get; set; }

        public DateTime date { get; set; } = DateTime.Now;

        public string CustomerId { get; set; }
        public Customer customer { get; set; }
    }
}

cw_db/Controllers/FeedbackController.cs
using cw_db.Interfaces;
using cw_db.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace cw_db.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly UserManager<Customer> userManager;
        private readonly IHttpContextAccessor httpContext;

        public FeedbackController(IUnitOfWork unitOfWork, UserManager<Customer> userManager, IHttpContextAccessor httpContext)
        {
            this.unitOfWork = unitOfWork;
            this.userManager = userManager;
            this.httpContext = httpContext;
        }

        public async Task<IActionResult> Index(string searchstring)
        {
            var model = await unitOfWork.Repo<Feedback>().GetAllAsync();

            if (!String.IsNullOrEmpty(searchstring))
            {
                model = unitOfWork.Repo<Feedback>().Find(s => s.Title.Contains(searchstring));
            }
            foreach (var item in model)
            {
                var userId = httpContext.HttpContext.User.Identity.Name;
                var user = await userManager.FindByIdAsync(item.CustomerId);
                item.customer = user;
            }
            return View("Index", model);
        }

        [HttpPost]
        public async Task<ActionResult> AddFeedback(Feedback feedback)
        {
            var userId = httpContext.HttpContext.User.Identity.Name;
            var user = await userManager.FindByEmailAsync(userId);
            feedback.customer = user;
            feedback.CustomerId = userId;
            feedback.date = DateTime.Now;
            unitOfWork.Repo<Feedback>().Add(feedback);
            await unitOfWork.Repo<Feedback>().SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

cw_db/Views/Feedback/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<Feedback>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by Title:<input type="text" name="searchstring"/>
            <button class="btn btn-dark" type="submit">Find</button>
            <a asp-action="Index">Back to full list</a>
        </p>
    </div>
</form>

<div class="text-center">
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model=>model.CustomerId)</th>

            <th>@Html.DisplayNameFor(model=>model.Title)</th>
            <th>@Html.DisplayNameFor(model=>model.Content)</th>
            <th>@Html.DisplayNameFor(model=>model.Rating)</th>
        </tr>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.customer.UserName</td>
                <td>@product.Title</td>
                <td>@product.Content</td>
                <td>@product.Rating</td>
            </tr>
        }
    </table>
    <div>
        @if (ViewContext.HttpContext.User.Identity.IsAuthenticated)
        {
                <form asp-controller="Feedback" asp-action="AddFeedback" method="post">
                <input type="text" class="form-control" placeholder="Title" name="Title" />
                <input type="text" class="form-control" placeholder="Content" name="Content" />
                <input type="text" class="form-control" placeholder="Rating" name="Rating" />
                <button class="btn btn-dark" type="submit">Create</button>
            </form>
        }
    </div>
    @*<h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
</div>